bev_size = 200
embed_dims = 128
sampling_locations = 5

model = dict(type='SegOneBEV',
             data_preprocessor=dict(type='ImgDataPreprocessor',
                                    mean=[0.485, 0.456, 0.406],
                                    std=[0.229, 0.224, 0.225],
                                    bgr_to_rgb=True),
             backbone=dict(
                 type='Backbone_VSSM',
                 out_indices=(0, 1, 2, 3),
                 pretrained="./pretrained/vssmtiny_dp01_ckpt_epoch_292.pth",
                 dims=96,
                 depths=(2, 2, 9, 2),
                 ssm_d_state=16,
                 ssm_dt_rank="auto",
                 ssm_ratio=2.0,
                 mlp_ratio=0.0,
                 downsample_version="v1",
                 patchembed_version="v1"),
             neck=dict(type='NeckOneBEV',
                       in_channels=[96, 192, 384, 768],
                       out_channels=embed_dims),
             view_trans=dict(
                 type='ProcessorOneBEV',
                 bev_h=bev_size,
                 bev_w=bev_size,
                 embed_dims=embed_dims,
                 positional_encoding=dict(type='mmdet.SinePositionalEncoding',
                                          num_feats=embed_dims // 2,
                                          normalize=True),
                 mvt=dict(type='MambaViewTransformation',
                         num_layers=4,
                         mvt_layers=dict(type='MVTLayer',
                                         sampling_cfgs=dict(
                                             type='Sampling',
                                             embed_dims=embed_dims,
                                             num_locations=sampling_locations),
                                         vssm_cfgs=dict(type='VSSM',
                                                        patch_size=sampling_locations,
                                                        in_chans=embed_dims,
                                                        depths=[2],
                                                        dims=embed_dims,
                                                        ssm_ratio=1.0,
                                                        mlp_ratio=0.0,
                                                        drop_path_rate=0.2,
                                                        norm_layer="ln")))),
             head=dict(type='HeadOneBEV',
                       embed_dims=embed_dims,
                       loss_type=dict(type='FocalLossBEV')))
